### ISSUE TITLE
Import multiple documents sometimes fail parsing response from Typesense server.

### ISSUE THREAD

**Issue by hortelanobruno-ol** [typesense/typesense-js#210]
## Description

Calling the import function with an array greater than 250 elements sometimes fails.

## Steps to reproduce

Initialize a collection with more than 250 elements and import that collection repeatedly.

```
const documents = [...];
for(var i = 0; i < 1000;i++){
 await tsClient
  .collections<T>('testcollection')
  .documents()
  .import(documents); // this fails
}
```

## Expected Behavior

It doesn't fail.

## Actual Behavior

It fails with this error:

> SyntaxError: Unexpected end of JSON input at JSON.parse () at /app/node_modules/.pnpm/typesense@[1.4.1_@babel](mailto:1.4.1_@babel)+runtime@7.21.0/node_modules/typesense/lib/Typesense/Documents.js:145:115 at Array.map () at Documents. (/app/node_modules/.pnpm/typesense@[1.4.1_@babel](mailto:1.4.1_@babel)+runtime@7.21.0/node_modules/typesense/lib/Typesense/Documents.js:145:84) at step (/app/node_modules/.pnpm/typesense@[1.4.1_@babel](mailto:1.4.1_@babel)+runtime@7.21.0/node_modules/typesense/lib/Typesense/Documents.js:48:23) at Object.next (/app/node_modules/.pnpm/typesense@[1.4.1_@babel](mailto:1.4.1_@babel)+runtime@7.21.0/node_modules/typesense/lib/Typesense/Documents.js:29:53) at fulfilled (/app/node_modules/.pnpm/typesense@[1.4.1_@babel](mailto:1.4.1_@babel)+runtime@7.21.0/node_modules/typesense/lib/Typesense/Documents.js:20:58) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5)

## Metadata

**Typesense Version**: 0.25.2

**OS**: Linux

**Comment by jasonbosco** [comment]
This is most likely because the code snippet you have makes 1K concurrent connections and Typesense is aborting those requests due to lack of CPU capacity. 

Could you try using [`for-await...of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of) when using promises inside of for loops?

**Comment by rdsedmundo** [comment]
@jasonbosco we continue to face this issue as well, and we have reported it to will back in Oct 2023 via our shared Slack channel. 

While I understand that you have an idea of what could be the root cause, I don't think the current behavior is desirable from a SDK still. Instead of trying to parse a malformed JSON response, perhaps it should read the HTTP's status code from the response—I assume the server is returning 429 or something—and throw a more appropriate error message.

And FWIW we're seeing this error when trying to bulk import 180 records at once (single call), so in our situation it may not be what you're saying. 

I just did a patch in the SDK to fully log the axios's response content and will report it later with what we're seeing.

**Comment by jasonbosco** [comment]
> perhaps it should read the HTTP's status code from the response

The import endpoint always returns a 200 by design, to account for partial successes / failures. 

The actual document-level errors are returned as JSONL in the API response body under normal circumstances. So if that response fails JSON parsing, then it's an unexpected server-side issue. 

In any case, let me know what you find. I would also recommend upgrading to the latest version of Typesense (in at least two older versions we had an issue where the server would return blank lines in the import API response, which could also cause this issue).
