### ISSUE TITLE
Make a smaller Bundle Size?

### ISSUE THREAD

**Issue by stephanoparaskeva** [typesense/typesense-js#36]
TypeSense JS for use in a React, or React Native apps has a massive bundle size of 1mb which is minified to 463kb. This is way too high to be used in production and adds ~3 seconds to page loading times on lower bandwidth connections. Like mobile phones or laptops on Public WiFi.

 Competitors in the scene have JS packages that are less that 30kb minified and are Tree-Shakeable. This isn't and I was wondering if there are any plans to substantially improve this issue?

[Here](https://bundlephobia.com/result?p=typesense@0.5.1) Is a link for clarity.

TypeSense JS also has 3 dependencies which are large in themselves, the biggest is 
@babel/runtime, & Axios.

**Comment by jasonbosco** [comment]
Thank you for bringing this up. This is now fixed in v0.5.2.

Based on [this](https://bundlephobia.com/result?p=typesense@0.5.2), we're now coming in at 8.5KB gzipped + minified:

<img width="467" alt="Screen Shot 2020-06-17 at 1 38 25 PM" src="https://user-images.githubusercontent.com/458383/84947897-dcdd4a00-b09f-11ea-90f8-d37d999e00ce.png">
